variables = {
	'AGbf' : 'AGbf Aggression',
	'ACbf' : 'ACbf Achievement',
	'ALbf' : 'ALbf Alienation',
	'ANOREX': 'ANOREX Anorexia Nervosa',
	'ANTTV' : 'ANTTV Antisocial Triumvirate',
	'AV': 'AV Avoidant PD', 
	'Academic_Performance' : 'Academic Performance In secondary school',
	'Alc_hist_1' :'Alc_hist_1 In your lifetime?',
	'Alc_hist_2' :'Alc_hist_2 during the last 12 months',
	'Alc_hist_3' :'Alc_hist_3 during the last 30 days',
	'Alcohol30_days_1' :'A30_days_1 over the last 30 days how many beers if any',
	'Alcohol30_days_2' : 'A30_days_2 over the last 30 days how many ciders if any',
	'Alcohol30_days_3' : 'A30_days_3 over the last 30 days how many alcopops if any',
	'Alcohol30_days_4': 'A30_days_4 over the last 30 days how much wine if any',
	'Alcohol30_days_5' : 'A30_days_5 over the last 30 days how many spirits if any',
	'Alcohol30_days5+' : 'Think back over the last 30 days. How many times (if any) have you had five or more drinks on one occasion?',
	'Alcohol_12mts_exp_1' :'A12mts_exp_1 during the last 12mths because of alcohol how often got into a physical fight',
	'Alcohol_12mts_exp_2':'A12mts_exp_2 had an accident or injury',
	'Alcohol_12mts_exp_3' :'A12mts_exp_3 had a serious problem with parents',
	'Alcohol_12mts_exp_4' : 'A12mts_exp_4 had serious problems with friends',
	'Alcohol_12mts_exp_5' :'A12mts_exp_5 performed porrly at school/work',
	'Alcohol_12mts_exp_6' :'A12mts_exp_6 victimised by robbery/theft',
	'Alcohol_12mts_exp_7' :'A12mts_exp_7 had trouble with police',
	'Alcohol_12mts_exp_8' :'A12mts_exp_8 hospitalised/admitted to an emergency school',
	'Alcohol_12mts_exp_9' :'A12mts_exp_9 engaged in sexual intercourse without a condom',
	'Alcohol_12mts_exp_10' :'A12mts_exp_10 engaged in sexual intercourse you regretted the next day',
	'ADHD' : 'ADHD Attention Deficit/Hyperactivity Disorder',
	'ADHD_Type' : 'ADHD_Type',
	'ADHD_Type2' :'ADHD_Type2 ADHD type reduced',
    'ADHDI' : 'ADHDI ADHD Hyperactivity-Impulsivity',
	'ADHDHYP' : 'ADHDHYP ADHD hyperactive type',
	'ADHDIMP' : 'ADHDIMP ADHD impulsive type',
	'ADHDINAT' :'ADHDINAT ADHD inattention type',
	'AGG' :'AGG DSM IV',
    'APA' :'APA DSM IV',
	'BO' : ' Bo Borderline PD',
	'BUL' : 'BUL Bulimia Nervosa',
	'CD' : 'CD Conduct Disorder',
	'CDA' : 'CDA Conduct Disorder-Agressive Subtype',
	'CDD': 'CDD Conduct Disorder-Delinquent Subtype',
	'CNbf' : 'CNbf Control vs Impulsivity', 
	'COLD' : 'COLD Emotional Coldness',
	'CONbf' : 'CONbf Constraint', 
	'Ctci_excit' : 'CTci_excit Child NS1: exploratory excitability vs. stoic rigidity',
	'Ctci_imp' : 'Ctci_imp CHILD NS2: impulsiveness vs. reflection total',
	'Ctci_extra': 'Ctci_extra CHILD NS3: extravagance vs. reserve',
	'Ctci_diso' : 'Ctci_diso CHILD NS4: disorderliness vs. regimentation',
	'Ctci_novseek' :'Ctci_novseek CHILD NS: NOVELTYSEEKING',
	'Chain_smoke_freq' :'Chain_smoke_freq how often do you chain smoke, one cigarett right after another',
	'CurentMedication' :'CurrentMedication any medication for any psych disorder',
	'DANGER':'DANGER Dangerousness',
	'DE':'DE Dependent PD',
	'DECM':'DECM Decision-Making Subscale',
	'DENIAL': 'DENIAL Tendency to deny blatant pathology',
	'DEP': 'DEP Major Depressive Disorder',
	'DIA': 'DIA ADHD diagnosis',
	'DIAtxt' : 'DIAtxt dia text',
	'DIAwhere' :'DIAwhere the clinic in which diagnosed',
	'DIAwho' :'DIAwho the doctor who gave the diagnosis',
	'DIAyr' :'DIAyr year diagnosed',
	'Drugs_1' :'On how many occasions (if any) have you used any of the following drugs; amphetamines, tranquilizers/ sedatives, ecstasy, LSD, crack, cocaine, relevin, heroin, "magic mushrooms", GHB, anabolic steroids? In your lifetime',
	'Drugs_2' :'During the last 12 months',
	'Drugs_3' :'During the last 30 days',
	'DPD' :'DPD Depressive PD',
	'DIS' :'DIS DSM IV disorder', 
	'DOB' : 'DOB date of birth',
	'Drunk_sc_1' : 'Drunk_sc_1 on a scale of 1-10 how drunk were you the last day you drank alcohol',
	'EDUyrs' :'Years of education',
	'EDUtxt' :'Years of education (text ADHD)',
	'EMODYS' :'EMODYS emotional problems',
	'ETH' :'ETH race/ethnicity',
	'EXF44': 'EXF44 Execuitve Functions of the Frontal Lobes', 
	'First_1': 'When did you first if ever drink beer',
	'First_2': 'When did you first if ever drink cider',
	'First_3': 'When did you first if ever drink alcopops',
	'First_4': 'When did you first if ever drink wine',
	'First_5': 'When did you first if ever drink spirits',
	'First_6': 'When did you first if ever get drunk on alcohol',
	'First_Marj_1': 'First_Marj_1 first consumed cannabis',
	'First_Marj_2' :'First_Marj_2 first start consume cannabis on a daily basis',
	'Freq_Smoke_Func' :'How often do you feel that you need a cigarette to help you function?',
	'GAD':'GAD generalised anxiety disorder',
	'Gender':'What is your gender?',
	'Group/club':'Were you an active part of a social group in secondary school',
	'HAN':'Hand dominance',
	'HAbf':'Hand avoidance',
	'HEI':'Height',
	'HI':'HI Histronic PD',
	'Intend_Smoke':'How often do you smoke cigarettes more than you intend to smoke',
	'LANG':'LANG language problems',
	'LEARN':'LEARN learning problems',
	'Last_alc':'When was the last time you drank alcohol?',
	'Last_bev_1':'Think of the last day you drank alcohol. Which of the following beverage(s) did you drink that day?. I never drink alcohol',
	'Last_bev_2':'Think of the last day you drank alcohol. Which of the following beverage(s) did you drink that day?. Beer',
	'Last_bev_3':'Think of the last day you drank alcohol. Which of the following beverage(s) did you drink that day?. Cider',
	'Last_bev_4':'Think of the last day you drank alcohol. Which of the following beverage(s) did you drink that day?. Alcopops',
	'Last_bev_5':'Think of the last day you drank alcohol. Which of the following beverage(s) did you drink that day?. Wine',
	'Last_bev_6':'Think of the last day you drank alcohol. Which of the following beverage(s) did you drink that day?. Spirits',
	'LifetimeSmoking':'How frequently you have smoked cigarettes in your life',
	'Likely_1':'How likely is it that each of the following things would happen to you personally, if you drank alcohol? Feel relaxed',
	'Likely_2':'Get in trouble  with police',
	'Likely_3':'Harm my health',
	'Likely_4':'Feel Happy',
	'Likely_5':'Forget my problems',
	'Likely_6':'Not be able to stop drinking',
	'Likely_7':'Get an hangover',
	'Likely_8':'Feel more friendly and outgoing',
	'Likely_9':'Do something i regret',
	'Likely_10':'Have a lot of fun',
	'Likely_11':'Feel sick',
	'MAR_ADHD':'MAR_ADHD Original marital status adhd',
	'MAR_ADHDtxt':'MAR_ADHD Original marital status adhd (text)',
	'MAR':'Rescored marital status (the one with 4 options)',
	'MAR_ERAB':'Original marital status erab',
	'MAR_UCD' :'Original marital status whelan lab questionnaire',
	'MATDEL':'MATDEL maturational delay',
	'MEM':'MEM memory problems',
	'METACOG':'METACOG language-memory-learning subscale',
	'MND':'MND mild neurocognitive disorder',
	'Mntincome':'What is your monthly income?',
	'Marj_1':'Marj_1 on how many occasions (if any) in your lifetime have you used cannabis',
	'Marj_2':'Marj_2 during the last 12 months',
	'Marj_3':'Marj_3 during the last 30 days',
	'NA':'NA narcissistic PD',
	'NEMAGbf':'Agentic Negative Emotionality',
	'NEMALbf':'Alienated Negative Emotionality',
	'NEMbf':'Negative Emotional Temperament',
 	'NEURODYS': 'NEUROPSYCHOLOGICAL DYSFUNCTION',
 	'OC':'OBSESSIVE-COMPULSIVE PD',
	'ODD':'OPPOSITIONAL DEFIANT DISORDER',
	'OTHDIA':'Please provide details of other psychiatric/psychological disorder(s).',
	'Occupation' : 'What is your current occupation?',
	'PA':'PARANOID PD',
	'PAG':'PASSIVE-AGGRESSIVE PD',
	'parent_ADHDchildDOB':'Date of birth of child with ADHD (Ask Parent for the Childs Date of birth)',
	'Parent_control':'Do you have a child with ADHD diagnosis?',
	'parent_yrADHDchilddx':'What year what your child diagnosed with ADHD?',
	'PCD':'POSTCONCUSSIONAL DISORDER',
	'PEMAGbf':'Agentic Positive Emotionality',
	'PEMCObf':'Communal Positive Emotionality',
	'PEMbf':'Positive Emotional Temperament',
	'PERCEPMO':'PERCEPTUAL MOTOR INTEGRATION PROBLEMS',
	'PTH':'PSYCHOTIC THINKING',
	'Past_month_smoke':'How frequently have you smoked cigarettes in the past 30 days?',
	'Pub_Freq_1':'Think back once more over the last 30 days. On how many occasions (if any) have you drunk beer, cider, alcopops, wine, or spirits in a pub, bar, restaurant, or nightclub (on-premise)? Beer',
	'Pub_Freq_2':'Cider',
	'Pub_Freq_3':'Alcopops',
	'Pub_Freq_4':'Wine',
	'Pub_Freq_5':'Spirits',
	'Pur_Freq_1':'Think back over the last 30 days. On how many occasions (if any) have you bought beer, cider, alcopops, wine, or spirits in a store (supermarket, off license, kiosk, or petrol station) for your own consumption (off-premise)? Beer',
	'Pur_Freq_2':'Cider',
	'Pur_Freq_3':'Alcopops',
	'Pur_Freq_4':'Wine',
	'Pur_Freq_5':'Spirits',
	'Rel_Practice':'How often do you attend religious (or spiritual) services or ceremonies?',
	'Religious_Identity':'How religious (or spiritual) are you?',
	'SAD':'SEPARATION ANXIETY DISORDER',
 	'SCbf': 'Social Closeness',
 	'SLEEP': 'SLEEP DISTURBANCES',
 	'sibling_ADHDsibDOB':'What is your siblings date of birth?',
 	'sibling_control':'Do you have a sibling with ADHD diagnosis?',
 	'sibling_yrADHDsibdix':'What year you sibling were diagnosed with ADHD',
 	'SOCANX': 'SOCIAL ANXIETY',
 	'SOCIN' : 'SOCIAL INAPPROPRIATENESS SUBSCALE',
	'SOCWITH':'SOCIAL WITHDRAWAL',
	'SOM' :'SOMATIC PROBLEMS',
	'SPbf': 'Social Potency',
	'SRbf' : 'Stress Reaction',
 	'ST': 'SCHIZOTYPAL PD',
 	'SUBCORT':'SUBCORTICAL-COORDINATION+TICS',
 	'SZ' : 'SCHIZOID PD',
 	'Sex': 'What is your biological sex?',
 	'Smok_hist_1':'first time smoked a cigarette?',
 	'Smok_hist_2':'first started smoking cigarettes on a daily basis?',
 	'Smok_hist_3': 'first started buying cigarettes?', 	
    'Smoker_Non_smoker':'Are you smoker or non-smoker?',
	'Sports_Frequency' : 'How often did you do some form of physical exercise during secondary school?',
	't_1':'Anxiety probabiily score subset 1',
	't_2':'Anxiety probabiily score subset 2',
	't_3':'Anxiety probabiily score subset 3',
	'TRBf':'Traditionalism',
	'Tried_cig':'Have you ever tried a cigarette',
	'Trips_Smoke':'How often do you make special trips to get cigarette',
	'UVbf':'Unlikely Virtues',
	'WBbf':'Wellbeing',
	'WEI':'Weight in Kg'
}